### ISSUE TITLE
I want to help contribute.

### ISSUE THREAD

**Issue by latishab** [matthewlai/JaxVidFlow#1]
Hey there, I saw your post from scubaboard, I want to help contribute and finish this project in a few months. Is that okay?

If yes, how far have you gone? I would like to collect some papers first too.

https://scubaboard.com/community/threads/trying-to-get-some-data-for-underwater-white-balance.651148/page-2

**Comment by latishab** [comment]
I was thinking of making the correction software to be deployable on MacOS and Windows, i'm not sure why would you pick Python as the language.

**Comment by matthewlai** [comment]
Hi @latishab yes of course!

This package is a library for fast general purpose video processing. I've been developing a GUI frontend for it over the past couple weeks as I have some free time over Christmas. That's in https://github.com/matthewlai/ReefShader

I'm trying to get it runnable in the next few days, and it would be a good starting point then if you want to contribute.

This is what the UI looks like right now (I can preview, but processing still needs to be ported over from the example script [here](https://github.com/matthewlai/JaxVidFlow/blob/main/examples/process_dive_video.py). The example script already works. I've already processed many videos with it. It's just not documented and has no GUI.

I chose Python because of JAX. For 4K video processing without GPU acceleration you are looking at single digit FPS even on very new computers. On my NVIDIA GPU I'm able to get about 50 FPS. JAX has a very nice high level API for writing accelerated tensor code that runs on many GPUs (and also generate fast CPU kernels with Eigen). I don't think there's currently an alternative in any other language.

**Comment by latishab** [comment]
Great! since I run everything on Mac. I'll try to run the scripts with Apple's Metal GPU. I'll also take a look at the UI too. Happy to work with you!

**Comment by matthewlai** [comment]
I have been doing that, too! On Mac JAX can compile into Metal Performance Shaders, but the plugin is still experimental, and on my M3 it's actually similar speed to CPU.

On my old Intel Mac with a Radeon GPU it was much faster, though.
